apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-postgres
  namespace: python-demo
spec:
  volumeName: api-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
