apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-jenkins
  namespace: jenkins
spec:
  volumeName: api-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
