apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/jenkins-data"
