apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: python-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: namhn89/fastapi:dev
        env:
          - name: DB_HOST
            value: postgres
          - name: DB_DATABASE
            value: your_database_name
          - name: DB_USERNAME
            value: your_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: DATABASE_URL
            value: postgresql://${DB_DATABASE}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: python-demo
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 31222
  selector:
    app: fastapi-app
